name: x_mobile_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.7.6"

dependencies:
  cupertino_icons: ^1.0.2
  either_dart: ^0.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  injectable: ^2.1.0
  logger: ^1.2.2
  equatable: ^2.0.5

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.4
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
