name: clean_arch_flutter_template
description: Clean Architecture based project
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.7.6"

dependencies:
  cloud_firestore: ^4.13.0
  cupertino_icons: ^1.0.6
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  go_router: ^12.1.0
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.3.2
  logger: ^2.0.2+1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
